region         = "us-east-1"
instance_type  = "t3.micro"
instance_name  = "dev-ec2"
subnet_name    = "repo-test"
sg_id          = "subnet-0e94cddd221fa628a"
key_name       = "my-key"
associate_public_ip = "true"
